version: '2'

services:
    web:
      build: .
      volumes:
        - .:/var/www/html:rw
      depends_on:
        - db
      ports:
        - "8080:80"

    db:
      image: mysql/mysql-server
      ports:
        - "3306:3306"
      volumes:
        - /var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: dev
        MYSQL_PASSWORD: mysql4Dev
        MYSQL_DATABASE: user